### ISSUE TITLE
Max Camera Zoom 

### ISSUE THREAD

**Issue by Novy81** [leatrix/leatrix-plus-wrath#187] opened 2022-12-16 06:31 UTC
i dont have it checked but on log in and reload it goes to max zoom any way

**Comment by leatrix** [comment] 2022-12-16 10:01
Disable other addons and test.  Leatrix Plus will only set 'Max camera zoom' if the setting is enabled.  If the setting is not enabled, no changes are made at all.  So if another addon is setting the max camera zoom level, Leatrix Plus won't override it if 'Max camera zoom' is not enabled.

If you still have trouble, enable the 'Max camera zoom' setting and then run **/ltp config**.  You should see that the camera distance is now **4**.  Now disable 'Max camera zoom' and run **/ltp config** again.  You should see that the camera distance is now **1.9**.  Now **/reload** your UI and run **/ltp config** again.  If the camera distance is above 1.9 or 2.0 then another addon is setting that.

**Comment by leatrix** [comment] 2022-12-20 01:20
This isn't caused by LTP so closing this but if you still need help, continue to post in this ticket.

**Closed by leatrix** 2022-12-20 01:20 UTC
Labels: help
